EmployeesManager/Controllers/EducationCategoryController.cs
using EmployeesManager.DAL.Interfaces;
using EmployeesManager.Model;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace EmployeesManager.Web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class EducationCategoryController : Controller
    {
        private readonly IEducationCategoryRepository _context;
        public EducationCategoryController(IEducationCategoryRepository context)
        {
            _context = context;
        }

        // GET: EducationCategoryController
        public ActionResult Index()
        {
            return View(_context.GetAll().ToList());
        }

        [HttpPost]
        public async Task<IActionResult> Index(string searchString)
        {
            var educationCategories = from c in _context.GetAll()
                             select c;

            if (!String.IsNullOrEmpty(searchString))
            {
                educationCategories = educationCategories.Where(c => (c.CategoryName.ToLower()).Contains(searchString));
            }

            return View(educationCategories.ToList());
        }

        // GET: EducationCategoryController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: EducationCategoryController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: EducationCategoryController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("CategoryName")] EducationCategory educationCategory)
        {
            if(ModelState.IsValid)
            {
                _context.Add(educationCategory);
                _context.Save();
                TempData["success"] = "Uspješno dodavanje nove kategorije!";
                return RedirectToAction("Index");
            }

            return View(educationCategory);
        }

        // GET: EducationCategoryController/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var educationCategory = _context.GetById((int)id);

            if (educationCategory == null)
            {
                return NotFound();
            }

            return View(educationCategory);
        }

        // POST: EducationCategoryController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, EducationCategory educationCategory)
        {
            if (id != educationCategory.EducationCategoryId)
            {
                return NotFound();
            }

            try
            {
                _context.Update(educationCategory);
                _context.Save();
                TempData["success"] = "Uspješno ažuriranje kategorije!";
                return RedirectToAction("Index");
            }
            catch { }
            return View(educationCategory);
        }

        // GET: EducationCategoryController/Delete/5
        public ActionResult Delete(int id)
        {
            var educationCategory = _context.GetById(id);

            if (educationCategory == null)
            {
                return NotFound();
            }

            return View(educationCategory);
        }

        // POST: EducationCategoryController/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeletePost(int id)
        {
            var educationCategory = _context.GetById(id);

            if (educationCategory == null)
            {
                return NotFound();
            }

            _context.Remove(educationCategory);
            _context.Save();
            TempData["success"] = "Uspješno brisanje kategorije!";
            return RedirectToAction("Index");
        }
    }
}

EmployeesManager/Views/EducationCategory/Create.cshtml
@using EmployeesManager.Model
@model EducationCategory

@{
    ViewData["Title"] = "Create";
}

<form method="post" asp-action="Create">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Unos nove kategorije edukacije</h2>
            <hr />
        </div>
        <div>
        <div class="form-group">
                <label asp-for="CategoryName" class="control-label"></label>
                <input asp-for="CategoryName" class="form-control" />
                <span asp-validation-for="CategoryName" class="text-danger"></span>
        </div>
         <br />
         <div class="row pt-4">
             <div class="col-6">
                 <button type="submit" class="btn btn-primary">Kreiraj</button>
            </div>
            <div class="col-6 text-end">
                <a asp-controller="EducationCategory" asp-action="Index" class="btn btn-secondary">Natrag na popis kategorija edukacija</a>
            </div>
         </div>
    </div>
</form>

EmployeesManager/Views/EducationCategory/Delete.cshtml
@using EmployeesManager.Model
@model EducationCategory

@{
    ViewData["Title"] = "Delete";
}

<form method="post" asp-action="Delete">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Brisanje kategorije edukacije</h2>
            <hr />
        </div>
        <div>
        <div class="form-group">
                <label asp-for="CategoryName" class="control-label"></label>
                <input asp-for="CategoryName" class="form-control" />
                <span asp-validation-for="CategoryName" class="text-danger"></span>
        </div>
            <br />
         <div class="row pt-4">
             <div class="col-6">
                 <button type="submit" class="btn btn-danger">Obriši kategoriju edukacije</button>
            </div>
            <div class="col-6 text-end">
                <a asp-controller="EducationCategory" asp-action="Index" class="btn btn-secondary">Natrag na popis kategorija edukacija</a>
            </div>
         </div>
    </div>
        </div>
</form>

EmployeesManager/Views/EducationCategory/Edit.cshtml
@using EmployeesManager.Model
@model EducationCategory

@{
    ViewData["Title"] = "Edit";
}

<form method="post" asp-action="Edit">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Ažuriranje kategorije edukacije</h2>
            <hr />
        <div class="form-group">
                <label asp-for="CategoryName" class="control-label"></label>
                <input asp-for="CategoryName" class="form-control" />
                <input type="hidden" asp-for="EducationCategoryId" class="form-control" />
                <span asp-validation-for="CategoryName" class="text-danger"></span>
        </div>
        <br />
         <div class="row pt-4">
             <div class="col-6">
                 <button type="submit" class="btn btn-primary">Spremi promjene</button>
            </div>
            <div class="col-6 text-end">
                <a asp-controller="EducationCategory" asp-action="Index" class="btn btn-secondary">Natrag na popis kategorija edukacija</a>
            </div>
         </div>
    </div>
    </div>
</form>

EmployeesManager/Views/EducationCategory/Index.cshtml
@using EmployeesManager.Model
@model IEnumerable<EducationCategory>
@{
    ViewData["Title"] = "Index";
}

<partial name="_Notification" />

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-12 text-end">
            <a asp-controller="EducationCategory" asp-action="Create" class="btn btn-primary"><i class="bi bi-person-plus-fill"></i> &nbsp; Nova kategorija edukacije</a>
        </div>
        <div class="col-6">
            <h2 class="text-primary">Popis kategorija edukacija</h2>
        </div>
        <br />
        <form asp-controller="EducationCategory" asp-action="Index" class="d-flex">
                            <input class="form-control me-sm-2" type="text" name="SearchString" placeholder="Pretraga po nazivu">
                            <button class="btn btn-secondary my-2 my-sm-0" type="submit">Pretraži</button>
</form>
    </div>
    <br /><br />
</div>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.Label("Naziv")
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CategoryName)
            </td>
            <td class="text-end">
                <div class="btn-group" role="group">
                    <a asp-controller="EducationCategory" asp-action="Edit" asp-route-id="@item.EducationCategoryId" class="btn btn-primary mx-2"><i class="bi bi-pen-fill"></i> &nbsp Uredi</a>
                     <a asp-controller="EducationCategory" asp-action="Delete" asp-route-id="@item.EducationCategoryId" class="btn btn-danger mx-2"><i class="bi bi-trash3-fill"></i> &nbsp Obriši</a> 
                </div>
            </td>
        </tr>
}
    </tbody>
</table>