EmployeesManager/Controllers/ClinicController.cs
using EmployeesManager.DAL.Interfaces;
using EmployeesManager.Model;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace EmployeesManager.Web.Controllers
{
    [Authorize(Roles ="Admin")]
    public class ClinicController : Controller
    {
        private readonly IClinicRepository _context;
        public ClinicController(IClinicRepository context)
        {
            _context = context;
        }

        // GET: ClinicController
        public ActionResult Index(string sortOrder, string searchString)
        {
            return View(_context.GetAll().ToList());
        }

        [HttpPost]
        public async Task<IActionResult> Index(string searchString)
        {
            var clinics = from c in _context.GetAll()
                            select c;

            if (!String.IsNullOrEmpty(searchString))
            {
                clinics = clinics.Where(c => (c.NameLong.ToLower()).Contains(searchString) || (c.NameShort.ToLower()).Contains(searchString));
            }

            return View(clinics.ToList());
        }

        // GET: ClinicController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ClinicController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ClinicController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("NameShort,NameLong,HeadClinic,Location")] Clinic clinic)
        {
            if(ModelState.IsValid)
            {
                _context.Add(clinic);
                _context.Save();
                TempData["success"] = "Uspješno dodavanje nove klinike!";
                return RedirectToAction("Index");
            }
            return View(clinic);
        }

        // GET: ClinicController/Edit/5
        public IActionResult Edit(int? id)
        {
            //var clinic = _context.GetById(id);

            if (id == null)
            {
                return NotFound();
            }

            var clinic = _context.GetById((int)id);

            if (clinic == null)
            {
                return NotFound();
            }

            return View(clinic);
        }

        // POST: ClinicController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("ClinicId,NameShort,NameLong,HeadClinic,Location")] Clinic clinic)
        {
            if(id != clinic.ClinicId)
            {
                return NotFound();
            }

            try
            {
                _context.Update(clinic);
                _context.Save();
                TempData["success"] = "Uspješno ažuriranje klinike!";
                return RedirectToAction("Index");
            }
            catch { }
            return View(clinic);
        }

        // GET: EducationController/Delete/5
        public ActionResult Delete(int id)
        {
            var clinic = _context.GetById(id);

            if (clinic == null)
            {
                return NotFound();
            }

            return View(clinic);
        }

        // POST: ClinicController/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeletePost(int id)
        {
            var clinic = _context.GetById(id);

            if (clinic == null)
            {
                return NotFound();
            }

            _context.Remove(clinic);
            _context.Save();
            TempData["success"] = "Uspješno brisanje klinike!";
            return RedirectToAction("Index");
        }
    }
}

EmployeesManager/Controllers/EmployeeController.cs
using ClosedXML.Excel;
using EmployeesManager.DAL;
using EmployeesManager.DAL.Interfaces;
using EmployeesManager.Model;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Data;
using System.Linq;

namespace EmployeesManager.Web.Controllers
{
    [Authorize(Roles = "Admin, User")]
    public class EmployeeController : Controller
    {
        private readonly IEmployeesRepository _context;
        private readonly IHealthCareRepository _healthCare;
        private readonly IEducationsRepository _contextEducation;
        public EmployeeController(IEmployeesRepository context, IHealthCareRepository healthCare, IEducationsRepository education)
        {
            _context = context;
            _healthCare = healthCare;
            _contextEducation = education;
        }

        public IActionResult Index()
        {
            return View(_context.GetAll().ToList());
        }

        [HttpPost]
        public async Task<IActionResult> Index(string searchString)
        {
            var employees = from e in _context.GetAll()
                         select e;

            if (!String.IsNullOrEmpty(searchString))
            {
                employees = employees.Where(e => (e.FirstName.ToLower()).Contains((searchString).ToLower()) || (e.LastName.ToLower()).Contains((searchString).ToLower()));
            }

            return View(employees.ToList());
        }

        public ActionResult Details(int id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            ViewBag.HealthcareName = Enum.GetNames(typeof(HealthcareName)).ToArray();
            var employee = _context.GetEmployee(id);

            if (employee == null)
            {
                return NotFound();
            }

            return View(employee);
        }

        public ActionResult DetailsEmployee(int id)
        {
            ViewBag.Educations = _contextEducation.GetAll();

            var employee = _context.GetEmployeeEducations(id);

            if (employee == null)
            {
                return NotFound();
            }

            return View("DetailsEmployee", employee);
        }

        // GET
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            ViewBag.HealthcareName = Enum.GetNames(typeof(HealthcareName)).ToArray();
            return View();
        }


        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult Create(Employee employee)
        {
            return RedirectToAction("Index");
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult CreateEmployee(Employee employee, string[] Step)
        {
            _context.Add(employee);
            _context.Save();
            var employees = _context.GetAll().OrderByDescending(x => x.EmployeeId).Take(1).LastOrDefault();
            List<Healthcare> Healthcare = new List<Healthcare>();
            foreach (var n in Step)
            {
                var data = n.Split(',');
                Healthcare.Add(new Healthcare
                {
                    HealthcareName = data[0],
                    ValidUntil = Convert.ToDateTime(data[1]),
                    Remark = data[2],
                    EmployeeId = employees.EmployeeId,
                });
            }
            _healthCare.AddRange(Healthcare);
            _healthCare.Save();
            return Json(true);

        }

        //GET
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            ViewBag.HealthcareName = Enum.GetNames(typeof(HealthcareName)).ToArray();
            var employee = _context.GetEmployee(id);

            if (employee == null)
            {
                return NotFound();
            }

            return View(employee);
        }

        //POST
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult EditEmployee(Employee employee, string[] Step)
        {
            _context.Update(employee);
            _context.Save();
            var healthCare = _healthCare.GetHealthCare(employee.EmployeeId);
            if (healthCare.Count > 0)
            {
                _healthCare.RemoveRange(healthCare);
                _healthCare.Save();
            }
            List<Healthcare> Healthcare = new List<Healthcare>();
            foreach (var n in Step)
            {
                var data = n.Split(',');
                Healthcare.Add(new Healthcare
                {
                    HealthcareName = data[0],
                    ValidUntil = Convert.ToDateTime(data[1]),
                    Remark = data[2],
                    EmployeeId = employee.EmployeeId,
                });
            }
            _healthCare.AddRange(Healthcare);
            _healthCare.Save();
            return Json(true);
        }

        // GET
        [Authorize(Roles = "Admin")]
        public IActionResult Delete(int id)
        {
            var employee = _context.GetById(id);

            if (employee == null)
            {
                return NotFound();
            }

            return View(employee);
        }

        // POST
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public IActionResult DeletePost(int id)
        {
            var employee = _context.GetById(id);

            if (employee == null)
            {
                return NotFound();
            }

            _context.Remove(employee);
            _context.Save();
            TempData["success"] = "Uspješno brisanje zaposlenika!";
            return RedirectToAction("Index");
        }

        
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public IActionResult CreateOrEdit(EmployeeViewModel emp)
        //{
        //    if(ModelState.IsValid)
        //    {
        //        //if (emp.EmployeeId == 0)
        //        //{
        //        //    foreach (Healthcare healthcare in emp.Healthcares)
        //        //    {
        //        //        if(healthcare.HealthcareName.ToString() == null)
        //        //        {
        //        //            emp.Healthcares.Remove(healthcare);
        //        //        }
        //        //    }
        //        //    _db.Employees.Add(GetEmployee(new Employee(), emp));
        //        //}

        //        if (emp.EmployeeId == 0)
        //            _db.Employees.Add(GetEmployee(new Employee(), emp));

        //        else
        //        {
        //            var exemp = _db.Employees.Find(emp.EmployeeId);

        //            if (exemp == null)
        //            {
        //                return NotFound();
        //            }
        //            _db.Entry(exemp).Reference(x => x.Address).Load();
        //            _db.Entry(exemp).Reference(x => x.Contact).Load();
        //            _db.Entry(exemp).Collection(x => x.Healthcares).Load();
        //            _db.Employees.Update(GetEmployee(exemp, emp));
        //        }

        //        _db.SaveChanges();
        //        TempData["success"] = emp.EmployeeId == 0 ? "Uspješno dodavanje novog zaposlenika!" : "Uspješno ažuriranje zaposlenika!";
        //        return RedirectToAction("Index");
        //    }
        //    return View(emp);
        //}

        [HttpPost]
        public IActionResult Export()
        {
            DataTable dt = new DataTable("Grid");
            dt.Columns.AddRange(new DataColumn[8] { new DataColumn("Ime"),
                                        new DataColumn("Prezime"),
                                        new DataColumn("OIB"),
                                        new DataColumn("MBO"),
                                        new DataColumn("Aktivnost"),
                                        new DataColumn("Datum rođenja"),
                                        new DataColumn("Ulica"),
                                        new DataColumn("Kućni broj") });

            var employees = from employee in this._context.GetAll()
                             select employee;

            foreach (var employee in employees)
            {
                dt.Rows.Add(employee.FirstName, employee.LastName, employee.OIB, employee.MBO, employee.Active, employee.BirthDate, employee.Street, employee.StreetNumber);
            }

            using (XLWorkbook wb = new XLWorkbook())
            {
                wb.Worksheets.Add(dt);
                using (MemoryStream stream = new MemoryStream())
                {
                    wb.SaveAs(stream);
                    return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "Employees.xlsx");
                }
            }
        }

        [HttpPost]
        public IActionResult ExportSingle(int id)
        {
            DataTable dt = new DataTable("Grid");
            dt.Columns.AddRange(new DataColumn[8] { new DataColumn("Ime"),
                                        new DataColumn("Prezime"),
                                        new DataColumn("OIB"),
                                        new DataColumn("MBO"),
                                        new DataColumn("Aktivnost"),
                                        new DataColumn("Datum rođenja"),
                                        new DataColumn("Ulica"),
                                        new DataColumn("Kućni broj") });

            Employee employee = _context.GetById(id);

            //foreach (var education in educations)
            //{

EmployeesManager/Controllers/InstituteController.cs
using EmployeesManager.DAL.Interfaces;
using EmployeesManager.Model;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace EmployeesManager.Web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class InstituteController : Controller
    {
        private readonly IInstituteRepository _context;
        public InstituteController(IInstituteRepository context)
        {
            _context = context;
        }

        // GET: InstituteController
        public ActionResult Index()
        {
            return View(_context.GetAll().ToList());
        }

        [HttpPost]
        public async Task<IActionResult> Index(string searchString)
        {
            var institutes = from i in _context.GetAll()
                              select i;

            if (!String.IsNullOrEmpty(searchString))
            {
                institutes = institutes.Where(i => (i.NameLong.ToLower()).Contains(searchString) || (i.NameShort.ToLower()).Contains(searchString));
            }

            return View(institutes.ToList());
        }

        // GET: InstituteController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: InstituteController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: InstituteController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Institute institute)
        {
            try
            {
                _context.Add(institute);
                _context.Save();
                TempData["success"] = "Uspješno dodavanje novog Zavoda!";
                return RedirectToAction("Index");
            }
            catch { }
            return View(institute);
        }

        // GET: InstituteController/Edit/5
        public ActionResult Edit(int id)
        {
            var institute = _context.GetById(id);

            if (institute == null)
            {
                return NotFound();
            }

            return View(institute);
        }

        // POST: InstituteController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Institute institute)
        {
            if (ModelState.IsValid)
            {
                _context.Update(institute);
                _context.Save();
                TempData["success"] = "Uspješno ažuriranje Zavoda!";
                return RedirectToAction("Index");
            }
            return View(institute);
        }

        // GET: InstituteController/Delete/5
        public ActionResult Delete(int id)
        {
            var institute = _context.GetById(id);

            if (institute == null)
            {
                return NotFound();
            }

            return View(institute);
        }

        // POST: InstituteController/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeletePost(int id)
        {
            var institute = _context.GetById(id);

            if (institute == null)
            {
                return NotFound();
            }

            _context.Remove(institute);
            _context.Save();
            TempData["success"] = "Uspješno brisanje Zavoda!";
            return RedirectToAction("Index");
        }
    }
}

EmployeesManager/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EmployeesManager</title>
    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />*@
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/bootTheme.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EmployeesManager.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    @*<a class="navbar-brand" asp-controller="Employee" asp-action="Index">Baza djelatnika</a>*@
    @if (User.IsInRole("Admin") || User.IsInRole("User"))
    {
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarColor02">
                        <ul class="navbar-nav me-auto">
                            @*<li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Početna</a>
                                </li>*@

                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Employee" asp-action="Index">Zaposlenici</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Education" asp-action="Index">Edukacije</a>
                            </li>
                            @if (User.IsInRole("Admin"))
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Sistematizacija</a>
                                    <div class="dropdown-menu">
                                        <a class="dropdown-item" asp-controller="Clinic" asp-action="Index">Klinike</a>
                                        <a class="dropdown-item" asp-controller="Institute" asp-action="Index">Zavodi</a>
                                        <a class="dropdown-item" asp-controller="Department" asp-action="Index">Odjeli</a>
                                        <a class="dropdown-item" asp-controller="Workplace" asp-action="Index">Radilišta</a>
                                    </div>
                                </li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Administracija</a>
                                    <div class="dropdown-menu">
                                        <a class="dropdown-item" asp-controller="EducationCategory" asp-action="Index">Kategorije edukacija</a>
                                        <a class="dropdown-item" asp-controller="EducationType" asp-action="Index">Vrste edukacija</a>
                                        <a class="dropdown-item" asp-controller="ParticipationType" asp-action="Index">Vrste sudjelovanja</a>
                                    </div>
                                </li>
                            }
                        </ul>
                        @* <form class="d-flex">
                            <input class="form-control me-sm-2" type="text" placeholder="Search">
                            <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                            </form>*@
                    </div>
                }
                <partial name="_LoginPartial" />
  </div>
</nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - EmployeesManager @*- <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy*@</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
   @* <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css"></script>*@
    @*<script src="https://cdn.datatables.net/1.11.5/css/dataTables.bootstrap4.min.css"></script>*@
    @*<script src="~/js/site.js" asp-append-version="true"></script>*@

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

EmployeesManager/Views/Shared/_Notification.cshtml
@if(TempData["success"] != null)
{
    <h2 class="alert alert-dismissible alert-success">@TempData["success"]</h2>
}

@if(TempData["error"] != null)
{
    <h2>@TempData["error"]</h2>
}