EmployeesManager/Controllers/EducationTypeController.cs
using EmployeesManager.DAL.Interfaces;
using EmployeesManager.Model;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace EmployeesManager.Web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class EducationTypeController : Controller
    {
        private readonly IEducationTypeRepository _context;
        public EducationTypeController(IEducationTypeRepository context)
        {
            _context = context;
        }

        // GET: EducationTypeController
        public ActionResult Index()
        {
            return View(_context.GetAll().ToList());
        }

        [HttpPost]
        public async Task<IActionResult> Index(string searchString)
        {
            var educationTypes = from t in _context.GetAll()
                                      select t;

            if (!String.IsNullOrEmpty(searchString))
            {
                educationTypes = educationTypes.Where(t => (t.EducationTypeName.ToLower()).Contains(searchString));
            }

            return View(educationTypes.ToList());
        }

        // GET: EducationTypeController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: EducationTypeController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: EducationTypeController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("EducationTypeName")] EducationType educationType)
        {
            if(ModelState.IsValid)
            {
                _context.Add(educationType);
                _context.Save();
                TempData["success"] = "Uspješno dodavanje novog tipa edukacije!";
                return RedirectToAction("Index");
            }
            return View(educationType);
        }

        // GET: EducationTypeController/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var educationType = _context.GetById((int)id);

            if (educationType == null)
            {
                return NotFound();
            }

            return View(educationType);
        }

        // POST: EducationTypeController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, EducationType educationType)
        {
            if (id != educationType.EducationTypeId)
            {
                return NotFound();
            }

            try
            {
                _context.Update(educationType);
                _context.Save();
                TempData["success"] = "Uspješno ažuriranje vrste edukacije!";
                return RedirectToAction("Index");
            }
            catch { }
            return View(educationType);
        }

        // GET: EducationTypeController/Delete/5
        public ActionResult Delete(int id)
        {
            var educationType = _context.GetById(id);

            if (educationType == null)
            {
                return NotFound();
            }

            return View(educationType);
        }

        // POST: EducationTypeController/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeletePost(int id)
        {
            var educationType = _context.GetById(id);

            if (educationType == null)
            {
                return NotFound();
            }

            _context.Remove(educationType);
            _context.Save();
            TempData["success"] = "Uspješno brisanje tipa edukacije!";
            return RedirectToAction("Index");
        }
    }
}

EmployeesManager/Views/EducationType/Create.cshtml
@using EmployeesManager.Model
@model EducationType

@{
    ViewData["Title"] = "Create";
}

<form method="post" asp-action="Create">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Unos nove vrste edukacije</h2>
            <hr />
        </div>
        <div>
        <div class="form-group">
                <label asp-for="EducationTypeName" class="control-label"></label>
                <input asp-for="EducationTypeName" class="form-control" />
                <span asp-validation-for="EducationTypeName" class="text-danger"></span>
        </div>
         <br />
         <div class="row pt-4">
             <div class="col-6">
                 <button type="submit" class="btn btn-primary">Kreiraj</button>
            </div>
            <div class="col-6 text-end">
                <a asp-controller="EducationType" asp-action="Index" class="btn btn-secondary">Natrag na popis vrsti edukacija</a>
            </div>
         </div>
    </div>
</form>

EmployeesManager/Views/EducationType/Delete.cshtml
@using EmployeesManager.Model
@model EducationType

@{
    ViewData["Title"] = "Delete";
}

<form method="post" asp-action="Delete">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Brisanje vrste edukacije</h2>
            <hr />
        </div>
        <div>
        <div class="form-group">
                <label asp-for="EducationTypeName" class="control-label"></label>
                <input asp-for="EducationTypeName" class="form-control" />
                <span asp-validation-for="EducationTypeName" class="text-danger"></span>
        </div>
            <br />
         <div class="row pt-4">
             <div class="col-6">
                 <button type="submit" class="btn btn-danger">Obriši vrstu edukacije</button>
            </div>
            <div class="col-6 text-end">
                <a asp-controller="EducationType" asp-action="Index" class="btn btn-secondary">Natrag na popis vrsta edukacija</a>
            </div>
         </div>
    </div>
        </div>
</form>

EmployeesManager/Views/EducationType/Edit.cshtml
@using EmployeesManager.Model
@model EducationType

@{
    ViewData["Title"] = "Edit";
}

<form method="post" asp-action="Edit">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Ažuriranje vrste edukacije</h2>
            <hr />
        <div class="form-group">
                <label asp-for="EducationTypeName" class="control-label"></label>
                <input asp-for="EducationTypeName" class="form-control" />
                <input type="hidden" asp-for="EducationTypeId" class="form-control" />
                <span asp-validation-for="EducationTypeName" class="text-danger"></span>
        </div>
        <br />
         <div class="row pt-4">
             <div class="col-6">
                 <button type="submit" class="btn btn-primary">Spremi promjene</button>
            </div>
            <div class="col-6 text-end">
                <a asp-controller="EducationType" asp-action="Index" class="btn btn-secondary">Natrag na popis vrsti edukacija</a>
            </div>
         </div>
    </div>
    </div>
</form>

EmployeesManager/Views/EducationType/Index.cshtml
@using EmployeesManager.Model
@model IEnumerable<EducationType>
@{
    ViewData["Title"] = "Index";
}

<partial name="_Notification" />

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-12 text-end">
            <a asp-controller="EducationType" asp-action="Create" class="btn btn-primary"><i class="bi bi-person-plus-fill"></i> &nbsp; Nova vrsta edukacije</a>
        </div>
        <div class="col-6">
            <h2 class="text-primary">Popis vrsta edukacija</h2>
        </div>
        <br />
        <form asp-controller="EducationType" asp-action="Index" class="d-flex">
                            <input class="form-control me-sm-2" type="text" name="SearchString" placeholder="Pretraga po nazivu">
                            <button class="btn btn-secondary my-2 my-sm-0" type="submit">Pretraži</button>
</form>
    </div>
    <br /><br />
</div>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.Label("Naziv")
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.EducationTypeName)
            </td>
            <td class="text-end">
                <div class="btn-group" role="group">
                    <a asp-controller="EducationType" asp-action="Edit" asp-route-id="@item.EducationTypeId" class="btn btn-primary mx-2"><i class="bi bi-pen-fill"></i> &nbsp Uredi</a>
                     <a asp-controller="EducationType" asp-action="Delete" asp-route-id="@item.EducationTypeId" class="btn btn-danger mx-2"><i class="bi bi-trash3-fill"></i> &nbsp Obriši</a> 
                </div>
            </td>
        </tr>
}
    </tbody>
</table>