EmployeesManager/Controllers/WorkplaceController.cs
using EmployeesManager.DAL.Interfaces;
using EmployeesManager.Model;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace EmployeesManager.Web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class WorkplaceController : Controller
    {
        private readonly IWorkplaceRepository _context;
        public WorkplaceController(IWorkplaceRepository context)
        {
            _context = context;
        }

        // GET: WorkplaceController
        public ActionResult Index()
        {
            return View(_context.GetAll().ToList());
        }

        [HttpPost]
        public async Task<IActionResult> Index(string searchString)
        {
            var workplaces = from w in _context.GetAll()
                              select w;

            if (!String.IsNullOrEmpty(searchString))
            {
                workplaces = workplaces.Where(w => (w.NameLong.ToLower()).Contains(searchString) || (w.NameShort.ToLower()).Contains(searchString));
            }

            return View(workplaces.ToList());
        }

        // GET: WorkplaceController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: WorkplaceController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: WorkplaceController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Workplace workplace)
        {
            try
            {
                _context.Add(workplace);
                _context.Save();
                TempData["success"] = "Uspješno dodavanje novog radilišta!";
                return RedirectToAction("Index");
            }
            catch { }
            return View(workplace);
        }

        // GET: WorkplaceController/Edit/5
        public ActionResult Edit(int id)
        {
            var workplace = _context.GetById(id);

            if (workplace == null)
            {
                return NotFound();
            }

            return View(workplace);
        }

        // POST: WorkplaceController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Workplace workplace)
        {
            if (ModelState.IsValid)
            {
                _context.Update(workplace);
                _context.Save();
                TempData["success"] = "Uspješno ažuriranje radilišta!";
                return RedirectToAction("Index");
            }
            return View(workplace);
        }

        // GET: WorkplaceController/Delete/5
        public ActionResult Delete(int id)
        {
            var workplace = _context.GetById(id);

            if (workplace == null)
            {
                return NotFound();
            }

            return View(workplace);
        }

        // POST: WorkplaceController/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeletePost(int id)
        {
            var workplace = _context.GetById(id);

            if (workplace == null)
            {
                return NotFound();
            }

            _context.Remove(workplace);
            _context.Save();
            TempData["success"] = "Uspješno brisanje radilišta!";
            return RedirectToAction("Index");
        }
    }
}

EmployeesManager/Views/Workplace/Create.cshtml
@using EmployeesManager.Model
@model Workplace

@{
    ViewData["Title"] = "Create";
}

<form method="post" asp-action="Create">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Unos novog radilišta</h2>
            <hr />
        </div>
        <div>
        <div class="form-group">
                <label asp-for="NameShort" class="control-label"></label>
                <input asp-for="NameShort" class="form-control" />
                <span asp-validation-for="NameShort" class="text-danger"></span>
        </div>
        <div class="form-group">
                <label asp-for="NameLong" class="control-label"></label>
                <input asp-for="NameLong" class="form-control" />
                <span asp-validation-for="NameLong" class="text-danger"></span>
        </div>
        <div class="form-group">
                <label asp-for="ExpenseCode" class="control-label"></label>
                <input asp-for="ExpenseCode" class="form-control" />
                <span asp-validation-for="ExpenseCode" class="text-danger"></span>
        </div>
         <br />
         <div class="row pt-4">
             <div class="col-6">
                 <button type="submit" class="btn btn-primary">Kreiraj</button>
            </div>
            <div class="col-6 text-end">
                <a asp-controller="Workplace" asp-action="Index" class="btn btn-secondary">Natrag na popis radilišta</a>
            </div>
         </div>
    </div>
</form>

EmployeesManager/Views/Workplace/Delete.cshtml
@using EmployeesManager.Model
@model Workplace

@{
    ViewData["Title"] = "Delete";
}

<form method="post" asp-action="Delete">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Brisanje radilišta</h2>
            <hr />
        </div>
        <div>
        <div class="form-group">
                <label asp-for="NameShort" class="control-label"></label>
                <input asp-for="NameShort" class="form-control" />
                <span asp-validation-for="NameShort" class="text-danger"></span>
        </div>
        <div class="form-group">
                <label asp-for="NameLong" class="control-label"></label>
                <input asp-for="NameLong" class="form-control" />
                <span asp-validation-for="NameLong" class="text-danger"></span>
        </div>
        <div class="form-group">
                <label asp-for="ExpenseCode" class="control-label"></label>
                <input asp-for="ExpenseCode" class="form-control" />
                <span asp-validation-for="ExpenseCode" class="text-danger"></span>
        </div>
            <br />
         <div class="row pt-4">
             <div class="col-6">
                 <button type="submit" class="btn btn-danger">Obriši radilište</button>
            </div>
            <div class="col-6 text-end">
                <a asp-controller="Workplace" asp-action="Index" class="btn btn-secondary">Natrag na popis radilišta</a>
            </div>
         </div>
    </div>
        </div>
</form>

EmployeesManager/Views/Workplace/Edit.cshtml
@using EmployeesManager.Model
@model Workplace

@{
    ViewData["Title"] = "Edit";
}

<form method="post" asp-action="Edit">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Ažuriranje radilišta</h2>
            <hr />
        </div>
        <div>
        <div class="form-group">
                <label asp-for="NameShort" class="control-label"></label>
                <input asp-for="NameShort" class="form-control" />
                <span asp-validation-for="NameShort" class="text-danger"></span>
        </div>
        <div class="form-group">
                <label asp-for="NameLong" class="control-label"></label>
                <input asp-for="NameLong" class="form-control" />
                <span asp-validation-for="NameLong" class="text-danger"></span>
        </div>
        <div class="form-group">
                <label asp-for="ExpenseCode" class="control-label"></label>
                <input asp-for="ExpenseCode" class="form-control" />
                <span asp-validation-for="ExpenseCode" class="text-danger"></span>
        </div>
            <br />
         <div class="row pt-4">
             <div class="col-6">
                 <button type="submit" class="btn btn-primary">Spremi promjene</button>
            </div>
            <div class="col-6 text-end">
                <a asp-controller="Workplace" asp-action="Index" class="btn btn-secondary">Natrag na popis radilišta</a>
            </div>
         </div>
    </div>
    </div>
</form>

EmployeesManager/Views/Workplace/Index.cshtml
@using EmployeesManager.Model
@model IEnumerable<Workplace>
@{
    ViewData["Title"] = "Index";
}

<partial name="_Notification" />

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-12 text-end">
            <a asp-controller="Workplace" asp-action="Create" class="btn btn-primary"><i class="bi bi-eyeglasses"></i> &nbsp; Novo radilište</a>
        </div>
        <div class="col-6">
            <h2 class="text-primary">Popis radilišta</h2>
        </div>
        <br />
        <form asp-controller="Workplace" asp-action="Index" class="d-flex">
                            <input class="form-control me-sm-2" type="text" name="SearchString" placeholder="Pretraga po šifri ili nazivu">
                            <button class="btn btn-secondary my-2 my-sm-0" type="submit">Pretraži</button>
</form>
    </div>
    <br /><br />
</div>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.Label("Šifra radilišta")
            </th>
            <th>
                @Html.Label("Naziv radilišta")
            </th>
            <th>
                @Html.Label("Mjesto troška")
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NameShort)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NameLong)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ExpenseCode)
            </td>
            
            <td>
                <div class="btn-group" role="group">
                    <a asp-controller="Workplace" asp-action="Edit" asp-route-id="@item.WorkplaceId" class="btn btn-primary mx-2"><i class="bi bi-pen-fill"></i> &nbsp Uredi</a>
                     <a asp-controller="Workplace" asp-action="Delete" asp-route-id="@item.WorkplaceId" class="btn btn-danger mx-2"><i class="bi bi-trash3-fill"></i> &nbsp Obriši</a> 
                </div>
            </td>
        </tr>
}
    </tbody>
</table>